spring: 
  profiles: 
    active: 
    - dev
    
---

spring: 
  profiles: dev
  application: 
    name: mircoservice-config-weiy-dev
      
---

spring: 
  profiles: test
  application: 
    name: mircoservice-config-weiy-test
      
#请保存为UTF-8的形式