spring: 
  profiles: 
    active: 
    - dev
    
---

server:
  port: 8201
  
spring: 
  profiles: dev
  application: 
    name: mircoservice-config-client
    
eureka:
  client:
    service-url:                              #服务注册到eureka服务端
      defaultZone: http://eureka-dev.com:7001/eureka/
      
---

server:
  port: 8202

spring: 
  profiles: test
  application: 
    name: mircoservice-config-client
    
eureka:
  client:
    service-url:                              #服务注册到eureka服务端
      defaultZone: http://eureka-test.com:7001/eureka/
      
#请保存为UTF-8的形式